# Generated by Django 5.1.4 on 2024-12-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
    ]
